improve emoji completion
rhysd/vim-gfm-syntax pull request #13
Opened 2021-09-25 12:26 UTC by cizmazia

- Strip the leading colon to include matches within the emoji names, not just from the beginning
- Cleanup: sort emojis

2021-09-25 18:08 UTC, rhysd requested changes

2021-09-25 18:08 UTC, rhysd commented on autoload/gfm_syntax/emoji.vim
> +        return filter(map(copy(s:EMOJIS),{_,v->v[0]}), {_,v->match(v, '[:_]'.a:base[1:])>=0})
I think calling `filter()` then `map()` is more efficient because filtered list contains fewer elements.

2021-09-25 18:08 UTC, rhysd commented on autoload/gfm_syntax/emoji.vim
> +        return filter(map(copy(s:EMOJIS),{_,v->v[0]}), {_,v->match(v, '[:_]'.a:base[1:])>=0})
```suggestion
        return filter(map(copy(s:EMOJIS),{_,v->v[0]}), {_,v->v =~# '[:_]'.a:base[1:]})
```

It looks `=~#` is sufficient to check the base is matched to a part of emoji name. Using operator is more efficient than using function call in Vim script.

2021-09-26 07:55 UTC, cizmazia commented
Dropping the request. Looking into:
https://github.com/junegunn/vim-emoji

2021-09-26 07:55 UTC, closed without merging